---
services:
  apache:
    hostname: $HOSTNAME
    image: "httpd:alpine"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data:/usr/local/apache2/htdocs/"
version: "3"
