---
services:
  apache:
    hostname: $HOSTNAME
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data:/usr/local/apache2/htdocs/"
version: "3"
